let data = ['EN',
        ['D:/Git/translate/test/TestFile/simpleTest/js/hello.js'],
        '我们不\"一样',
        '宏控制词条',
        '宏不一样所以肯定被提取',
        '没有对应的结束宏，可以被提取',
        '符号提(\')取验(")证项',
        '换行和tab验证：',
        '时间组一：',
        '类型：',
        '系统日志',
        'Attack \'Log"',
        '错误日志',
        'Log \n Content'
    ],
    data_cn = ['CN',
        ['D:/Git/translate/test/TestFile/simpleTest/js/hello.js'],
        '我们不\"一样',
        '宏控制词条',
        '宏不一样所以肯定被提取',
        '没有对应的结束宏，可以被提取',
        '符号提(\')取验(")证项',
        '换行和tab验证：',
        '时间组一：',
        '类型：',
        '系统日志',
        '错误日志'
    ],
    data_all = ['EN',
        ['D:/Git/translate/test/TestFile/simpleTest/js/hello.js'],
        '我们不"一样',
        '这条肯定不能被提取',
        '宏控制词条',
        '宏不一样所以肯定被提取',
        '没有对应的结束宏，可以被提取',
        '符号提(\')取验(")证项',
        '换行和tab验证：',
        '时间组一：',
        '类型：',
        '系统日志',
        'Attack \'Log"',
        '错误日志',
        'Log \n Content'
    ];

module.exports = {
    data,
    data_cn,
    data_all
}